name: cms-env3
channels:
- bioconda
- defaults
dependencies:
- python
- alabaster=0.7.8
- babel=2.3.3
- bcftools=1.3.1
- boltons=16.4.1
- curl=7.45.0=1
- htslib=1.3.1=0
- peewee=2.8.0
- pysam=0.9.1
- python-dateutil=2.3
- samtools=1.3.1
- selscan=1.1.0b
- biopython=1.67
- cloog=0.18.0
- docutils=0.12
- ecdsa=0.13
- gcc=4.8.5=3
- gmp=5.1.2
- imagesize=0.7.1
- isl=0.12.2
- jinja2=2.8
- libgcc=4.8.5
- matplotlib=1.5.1
- markupsafe=0.23
- mkl=11.3.3
- mpc=1.0.1
- mpfr=3.1.2
- ncurses=5.9
- numpy=1.11.0
- openssl=1.0.2h
- pandas=0.18.1
- paramiko=1.16.0
- pip=8.1.2
- pycrypto=2.6.1
- pygments=2.1.3
- python=3.5.1
- pytz=2016.4
- readline=6.2
- scipy=0.17.1
- setuptools=23.0.0
- six=1.10.0
- snowballstemmer=1.2.1
- sphinx_rtd_theme=0.1.9
- sqlite=3.13.0
- tk=8.5.18
- wheel=0.29.0
- xz=5.0.5
- zlib=1.2.8
- pip:
  - apipkg==1.4
  - boltons==16.4.1
  - coverage==4.1
  - coveralls==1.1
  - docopt==0.6.2
  - execnet==1.4.1
  - flake8==2.6.0
  - mccabe==0.5.0
  - mock==2.0.0
  - numpy==1.11.0
  - pbr==1.10.0
  - peewee==2.8.0
  - py==1.4.31
  - pycodestyle==2.0.0
  - pyflakes==1.2.3
  - pysam==0.9.1
  - pytest==2.9.2
  - pytest-cov==2.2.1
  - pytest-xdist==1.14
  - python-dateutil==2.3
  - requests==2.10.0
  - sphinx==1.4.4
  - sphinx-argparse==0.1.15
  - sphinx-rtd-theme==0.1.9

